MvcOnlineTicariOtomasyonSistemi/MvcOnlineTicariOtomasyonSistemi/Controllers/FaturaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcOnlineTicariOtomasyonSistemi.Models.Siniflar;
namespace MvcOnlineTicariOtomasyonSistemi.Controllers
{
    public class FaturaController : Controller
    {
        // GET: Fatura
        Context c = new Context();
        public ActionResult Index()
        {
            var sorgu = c.Faturalars.ToList();
            return View(sorgu);
        }
        [HttpGet]
        public ActionResult FaturaEkle()
        {
            return View();
        }
        [HttpPost]
        public ActionResult FaturaEkle(Faturalar f)
        {
            c.Faturalars.Add(f);
            c.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult FaturaGetir(int id)
        {
            var sorgu = c.Faturalars.Find(id);
            return View("FaturaGetir",sorgu);
        }
        public ActionResult FaturaGuncelle(Faturalar f)
        {
            var sorgu = c.Faturalars.Find(f.FaturaId);
            sorgu.FaturaSeriNo = f.FaturaSeriNo;
            sorgu.FaturaSiraNo = f.FaturaSiraNo;
            sorgu.FaturaTarih = f.FaturaTarih;
            sorgu.VergiDairesi = f.VergiDairesi;
            sorgu.FaturaSaati = f.FaturaSaati;
            sorgu.TeslimEden = f.TeslimEden;
            sorgu.TeslimAlan = f.TeslimAlan;
            c.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult FaturaDetay(int id)
        {
            var detayfatura = c.FaturaKalems.Where(x => x.FaturaId == id).ToList();
            //var ftrid = c.FaturaKalems.Where(x => x.FaturaId == id).Select(y => y.FaturaId).FirstOrDefault();
            //ViewBag.fid = ftrid;
            return View(detayfatura);
        }
        [HttpGet]
        public ActionResult FaturaKalemEkle(/*int id*/)
        {
            //var ftrid = c.FaturaKalems.Where(x => x.FaturaId == id).Select(y => y.FaturaId).FirstOrDefault();
            //ViewBag.fid = ftrid;                  
            return View();
        }
        [HttpPost]
        public ActionResult FaturaKalemEkle(FaturaKalem k)
        {         
            c.FaturaKalems.Add(k);
            c.SaveChanges();
            return RedirectToAction("Index");
        }
        
        public PartialViewResult Partial1()
        {
            var detayfatura = c.FaturaKalems.Where(x => x.FaturaId == 1).ToList();
            return PartialView(detayfatura);
        }

        public ActionResult Dinamik() 
        {
            Class3 cs = new Class3();
            cs.deger1 = c.Faturalars.ToList();
            cs.deger2 = c.FaturaKalems.ToList();
            return View(cs);
        }
        public ActionResult FaturaKaydet(string FaturaSeriNo, string FaturaSiraNo, DateTime FaturaTarih, string
            FaturaSaati, string TeslimEden, string TeslimAlan, string VergiDairesi, string Toplam, FaturaKalem[] kalemler)
        {
            Faturalar f = new Faturalar();
            f.FaturaSeriNo = FaturaSeriNo;
            f.FaturaSiraNo = FaturaSiraNo;
            f.FaturaTarih = FaturaTarih;
            f.FaturaSaati = FaturaSaati;
            f.TeslimEden = TeslimEden;
            f.TeslimAlan = TeslimAlan;
            f.VergiDairesi = VergiDairesi;
            f.Toplam = decimal.Parse(Toplam);
            c.Faturalars.Add(f);
            foreach (var x in kalemler)
            {
                FaturaKalem fk = new FaturaKalem();
                fk.Aciklama = x.Aciklama;
                fk.BirimFiyat = x.BirimFiyat;
                fk.FaturaId = x.FaturaKalemId;
                fk.Miktar = x.Miktar;
                fk.Tutar = x.Tutar;
                c.FaturaKalems.Add(fk);
            }
            c.SaveChanges();
            return Json("İşlem Başarılı", JsonRequestBehavior.AllowGet);
        }
      
    }
}

MvcOnlineTicariOtomasyonSistemi/MvcOnlineTicariOtomasyonSistemi/Controllers/KategoriController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcOnlineTicariOtomasyonSistemi.Models.Siniflar;
using PagedList;
using PagedList.Mvc;
namespace MvcOnlineTicariOtomasyonSistemi.Controllers
{
    public class KategoriController : Controller
    {
        // GET: Kategori

        Context c = new Context();//context sınıfından bir nesne türettim
        public ActionResult Index(int sayfa=1)
        {
            var degerler = c.Kategoris.ToList().ToPagedList(sayfa,4);//kategori tablosundaki sütunlara git bunu değerler değişkenine ata

            return View(degerler);//sonra geri degerler değişkenini döndürür 
        }
        //form yüklendiği zaman burayı(alttakini)çalıştır
        [HttpGet]
        public ActionResult KategoriEkle()
        {
            return View(); //KategoriEkle.cshtml sayfasını çalıştırır
        }
        //butona tıklandığında ekleme yapmak için burayı çalıştırır
        [HttpPost]
        public ActionResult KategoriEkle(Kategori k)
        {
            c.Kategoris.Add(k); //veritabanına ekliyor
            c.SaveChanges(); //değişlikleri kaydediyor
            return RedirectToAction("Index"); //Index Fonsiyonuna gider
        }

        public ActionResult KategoriSil(int id)
        {
            var sorgu = c.Kategoris.Find(id);
            c.Kategoris.Remove(sorgu);
            c.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult KategoriGetir(int id)
        {
            var sorgu = c.Kategoris.Find(id);            
            return View("KategoriGetir",sorgu);
        }

        public ActionResult KategoriGuncelle(Kategori k)
        {
            var sorgu = c.Kategoris.Find(k.KategoriId);
            sorgu.KategoriAd = k.KategoriAd;
            c.SaveChanges();
            return RedirectToAction("Index");
        }

        //Cascading işlemi için aşağıdaki actionı oluşturduk.
        public ActionResult Deneme() 
        {
            Class2 cs = new Class2();
            cs.Kategoriler = new SelectList(c.Kategoris, "KategoriId", "KategoriAd");
            cs.Urunler = new SelectList(c.Uruns, "UrunId", "UrunAd");
            return View(cs);
        }
        public JsonResult UrunGetir(int p) 
        {
            var UrunListesi = (from x in c.Uruns
                               join y in c.Kategoris
                               on x.Kategori.KategoriId equals y.KategoriId
                               where x.Kategori.KategoriId == p
                               select new
                               {
                                   Text = x.UrunAd,
                                   Value = x.UrunId.ToString()
                               }).ToList();
            return Json(UrunListesi, JsonRequestBehavior.AllowGet);                   

        }

    }
}

MvcOnlineTicariOtomasyonSistemi/MvcOnlineTicariOtomasyonSistemi/Views/Shared/_AdminLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>MVC5 İle Online Ticari Otomasyon Sistemi</title>
    <link href="~/Web/dist/css/styles.css" rel="stylesheet" />
    <link href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css" rel="stylesheet" crossorigin="anonymous" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/js/all.min.js" crossorigin="anonymous"></script>
</head>
<body class="sb-nav-fixed">
    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
        <a class="navbar-brand" href="index.html">Ticari Otomasyon</a>
        <button class="btn btn-link btn-sm order-1 order-lg-0" id="sidebarToggle" href="#"><i class="fas fa-bars"></i></button>
        <!-- Navbar Search-->
        <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
            <div class="input-group">
                <input class="form-control" type="text" placeholder="Aranacak Kelimeyı Girin..." aria-label="Search" aria-describedby="basic-addon2" />
                <div class="input-group-append">
                    <button class="btn btn-primary" type="button"><i class="fas fa-search"></i></button>
                </div>
            </div>
        </form>
        <!-- Navbar-->
        <ul class="navbar-nav ml-auto ml-md-0">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="userDropdown" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                    <a class="dropdown-item" href="/Alertler/Index/">Alertler</a>
                    <a class="dropdown-item" href="#">Ayarlar</a>
                    <a class="dropdown-item" href="#">Hesabım</a>
                    <a class="dropdown-item" href="/QR/Index/">OR Kodu Oluşturma</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">Çıkış Yap</a>
                </div>
            </li>
        </ul>
    </nav>
    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                <div class="sb-sidenav-menu">
                    <div class="nav">
                        <div class="sb-sidenav-menu-heading">İşlemler</div>
                        <a class="nav-link" href="/Kategori/Index/">
                            <div class="sb-nav-link-icon"><i class="fas fa-th-list"></i></div>
                            Kategoriler
                        </a>
                        <a class="nav-link" href="/Kategori/Deneme/">
                            <div class="sb-nav-link-icon"><i class="fas fa-th-list"></i></div>
                            Kategoriler-Ürünler Cascading
                        </a>
                        <a class="nav-link" href="/Urun/Index/">
                            <div class="sb-nav-link-icon"><i class="fas fa-barcode"></i></div>
                            Ürünler
                        </a>
                        <a class="nav-link" href="/Departman/Index/">
                            <div class="sb-nav-link-icon"><i class="fas fa-bars"></i></div>
                            Departmanlar
                        </a>
                        <a class="nav-link" href="/Cariler/Index/">
                            <div class="sb-nav-link-icon"><i class="fas fa-user"></i></div>
                            Cariler
                        </a>
                        <a class="nav-link" href="/Personel/Index/">
                            <div class="sb-nav-link-icon"><i class="fas fa-street-view"></i></div>
                            Personeller
                        </a>
                        <a class="nav-link" href="/Personel/PersonelListe/">
                            <div class="sb-nav-link-icon"><i class="fas fa-users"></i></div>
                            Personel Listesi
                        </a>
                        <a class="nav-link" href="/Galeri/Index/">
                            <div class="sb-nav-link-icon"><i class="fas fa-camera"></i></div>
                            Resim Galerisi
                        </a>
                        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages" aria-expanded="false" aria-controls="collapsePages">
                            <div class="sb-nav-link-icon"><i class="fas fa-book-open"></i></div>
                            Yönetici
                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </a>
                        <div class="collapse" id="collapsePages" aria-labelledby="headingTwo" data-parent="#sidenavAccordion">
                            <nav class="sb-sidenav-menu-nested nav accordion" id="sidenavAccordionPages">
                                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#pagesCollapseAuth" aria-expanded="false" aria-controls="pagesCollapseAuth">
                                    Yetkilendirme
                                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                                </a>
                                <div class="collapse" id="pagesCollapseAuth" aria-labelledby="headingOne" data-parent="#sidenavAccordionPages">
                                    <nav class="sb-sidenav-menu-nested nav">
                                        <a class="nav-link" href="login.html">Giriş</a>
                                        <a class="nav-link" href="register.html">Çıkış</a>
                                        <a class="nav-link" href="password.html">Şifremİ Unuttum</a>
                                    </nav>
                                </div>

                            </nav>
                        </div>

                        <div class="sb-sidenav-menu-heading">Rapor / Fatura</div>
                        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseLayouts" aria-expanded="false" aria-controls="collapseLayouts">
                            <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                            Grafikler
                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </a>
                        <div class="collapse" id="collapseLayouts" aria-labelledby="headingOne" data-parent="#sidenavAccordion">
                            <nav class="sb-sidenav-menu-nested nav">
                                <a class="nav-link" href="/Grafik/Index5/">Pie Grafik</a>
                                <a class="nav-link" href="/Grafik/Index7/">Column Grafik</a>
                                <a class="nav-link" href="/Grafik/Index6/">Line Grafik</a>
                            </nav>
                        </div>
                        <a class="nav-link" href="/Satis/Index/">
                            <div class="sb-nav-link-icon"><i class="fas fa-car"></i></div>
                            Satış Hareketleri
                        </a>
                        <a class="nav-link" href="/Fatura/Index/">
                            <div class="sb-nav-link-icon"><i class="fas fa-calendar"></i></div>
                            Faturalar
                        </a>
                        <a class="nav-link" href="/Fatura/Dinamik/">
                            <div class="sb-nav-link-icon"><i class="fas fa-procedures"></i></div>
                            Dinamik Faturalar
                        </a>
                        <a class="nav-link" href="index.html">
                            <div class="sb-nav-link-icon"><i class="fas fa-gift"></i></div>
                            Giderler
                        </a>

                        <a class="nav-link" href="/Kargo/Index/">
                            <div class="sb-nav-link-icon"><i class="fas fa-box"></i></div>
                            Kargo
                        </a>
                        <a class="nav-link" href="/Istatistik/Index/">
                            <div class="sb-nav-link-icon"><i class="fas fa-database"></i></div>
                            İstatistikler
                        </a>
                        <a class="nav-link" href="/Yapilacak/Index/">
                            <div class="sb-nav-link-icon"><i class="fas fa-calendar"></i></div>
                            Programlarım
                        </a>
                        @if (User.IsInRole("A"))
                        {
                            <a class="nav-link" href="/Istatistik/KolayTablolar/">
                                <div class="sb-nav-link-icon"><i class="fas fa-space-shuttle"></i></div>
                                Hızlı Bakış
                            </a>
                        }

                    </div>
                </div>
                <div class="sb-sidenav-footer">
                    <div class="small">Logged in as:</div>
                    Start Bootstrap
                </div>
            </nav>
        </div>
        <div id="layoutSidenav_content">
            
                    
                    @RenderBody()
                  
                                  
            <footer class="py-4 bg-light mt-auto">
                <div class="container-fluid">
                    <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted">Copyright &copy; Your Website 2020</div>
                        <div>
                            <a href="#">Privacy Policy</a>
                            &middot;
                            <a href="#">Terms &amp; Conditions</a>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </div>
    @*<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" crossorigin="anonymous"></script>*@
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    <script src="~/Web/dist/js/scripts.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
    <script src="~/Web/dist/assets/demo/chart-area-demo.js"></script>
    <script src="~/Web/dist/assets/demo/chart-bar-demo.js"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js" crossorigin="anonymous"></script>
    <script src="~/Web/dist/assets/demo/datatables-demo.js"></script>
</body>
</html>

MvcOnlineTicariOtomasyonSistemi/MvcOnlineTicariOtomasyonSistemi/Views/Shared/_CariLayout.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Müşteri Paneli/Takip Sistemi</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="~/Web2/plugins/fontawesome-free/css/all.min.css">
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="~/Web2/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css">
    <link rel="stylesheet" href="~/Web2/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
    <link rel="stylesheet" href="~/Web2/plugins/jqvmap/jqvmap.min.css">
    <link rel="stylesheet" href="~/Web2/dist/css/adminlte.min.css">
    <link rel="stylesheet" href="~/Web2/plugins/overlayScrollbars/css/OverlayScrollbars.min.css">
    <link rel="stylesheet" href="~/Web2/plugins/daterangepicker/daterangepicker.css">
    <link rel="stylesheet" href="~/Web2/plugins/summernote/summernote-bs4.css">
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>
<body class="hold-transition sidebar-mini layout-fixed">
    <div class="wrapper">
        <nav class="main-header navbar navbar-expand navbar-white navbar-light">          
            <ul class="navbar-nav ml-auto">
                <li class="nav-item dropdown">
                    <a class="nav-link" data-toggle="dropdown" href="#">
                        <i class="far fa-comments"></i>
                        <span class="badge badge-danger navbar-badge">3</span>
                    </a>
                    <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                        <a href="#" class="dropdown-item">
                            <div class="media">
                                <img src="~/Web2/dist/img/user1-128x128.jpg" alt="User Avatar" class="img-size-50 mr-3 img-circle">
                                <div class="media-body">
                                    <h3 class="dropdown-item-title">
                                        Brad Diesel
                                        <span class="float-right text-sm text-danger"><i class="fas fa-star"></i></span>
                                    </h3>
                                    <p class="text-sm">Call me whenever you can...</p>
                                    <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
                                </div>
                            </div>
                        </a>
                        <div class="dropdown-divider"></div>
                        <a href="#" class="dropdown-item">
                            <div class="media">
                                <img src="~/Web2/dist/img/user8-128x128.jpg" alt="User Avatar" class="img-size-50 img-circle mr-3">
                                <div class="media-body">
                                    <h3 class="dropdown-item-title">
                                        John Pierce
                                        <span class="float-right text-sm text-muted"><i class="fas fa-star"></i></span>
                                    </h3>
                                    <p class="text-sm">I got your message bro</p>
                                    <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
                                </div>
                            </div>
                        </a>
                        <div class="dropdown-divider"></div>
                        <a href="#" class="dropdown-item">
                            <div class="media">
                                <img src="~/Web2/dist/img/user3-128x128.jpg" alt="User Avatar" class="img-size-50 img-circle mr-3">
                                <div class="media-body">
                                    <h3 class="dropdown-item-title">
                                        Nora Silvester
                                        <span class="float-right text-sm text-warning"><i class="fas fa-star"></i></span>
                                    </h3>
                                    <p class="text-sm">The subject goes here</p>
                                    <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
                                </div>
                            </div>
                        </a>
                        <div class="dropdown-divider"></div>
                        <a href="#" class="dropdown-item dropdown-footer">See All Messages</a>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link" data-toggle="dropdown" href="#">
                        <i class="far fa-bell"></i>
                        <span class="badge badge-warning navbar-badge">15</span>
                    </a>
                    <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                        <span class="dropdown-item dropdown-header">15 Notifications</span>
                        <div class="dropdown-divider"></div>
                        <a href="#" class="dropdown-item">
                            <i class="fas fa-envelope mr-2"></i> 4 new messages
                            <span class="float-right text-muted text-sm">3 mins</span>
                        </a>
                        <div class="dropdown-divider"></div>
                        <a href="#" class="dropdown-item">
                            <i class="fas fa-users mr-2"></i> 8 friend requests
                            <span class="float-right text-muted text-sm">12 hours</span>
                        </a>
                        <div class="dropdown-divider"></div>
                        <a href="#" class="dropdown-item">
                            <i class="fas fa-file mr-2"></i> 3 new reports
                            <span class="float-right text-muted text-sm">2 days</span>
                        </a>
                        <div class="dropdown-divider"></div>
                        <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
                    </div>
                </li>               
            </ul>
        </nav>
        <aside class="main-sidebar sidebar-dark-primary elevation-4">
            <a href="/CariPanel/Index/" class="brand-link">                
                <span class="brand-text font-weight-light">CARİ PANELİ TAKİP SİSTEMİ</span>
            </a>
            <div class="sidebar">
                <nav class="mt-2">
                    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                        <li class="nav-item has-treeview menu-open">
                            <a href="/CariPanel/Index/" class="nav-link">
                                <i class="nav-icon fas fa-tachometer-alt"></i>
                                <p>
                                    PROFİLİM
                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="/CariPanel/Siparislerim/" class="nav-link">
                                <i class="nav-icon fas fa-th"></i>
                                <p>
                                    SİPARİŞLERİM
                                </p>
                            </a>
                        </li>
                        <li class="nav-item has-treeview">
                            <a href="/CariPanel/GelenMesajlar/" class="nav-link">
                                <i class="nav-icon fas fa-copy"></i>
                                <p>
                                    MESAJLARIM
                                </p>
                            </a>

                        </li>
                        <li class="nav-item has-treeview">
                            <a href="/CariPanel/KargoTakip/" class="nav-link">
                                <i class="nav-icon fas fa-chart-pie"></i>
                                <p>
                                    KARGO TAKİP

                                </p>
                            </a>
                        </li>
                        <li class="nav-item has-treeview">
                            <a href="/CariPanel/Cikis/" class="nav-link">
                                <i class="nav-icon fas fa-tree"></i>
                                <p>
                                    ÇIKIŞ

                                </p>
                            </a>
                        </li>
                    </ul>
                </nav>
            </div>
        </aside>
        <div class="content-wrapper">
            <div class="content-header">
                <div class="container-fluid">
                    <div class="row mb-2">
                        
                    </div>
                </div>
            </div>
            <section class="content">
                <div class="container-fluid">
                    @RenderBody()

                </div>
            </section>
        </div>
        <footer class="main-footer">          
        </footer>
        <aside class="control-sidebar control-sidebar-dark">
        </aside>
    </div>
    <script src="~/Web2/plugins/jquery/jquery.min.js"></script>
    <script src="~/Web2/plugins/jquery-ui/jquery-ui.min.js"></script>
    <script>
        $.widget.bridge('uibutton', $.ui.button)
    </script>
    <script src="~/Web2/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/Web2/plugins/chart.js/Chart.min.js"></script>
    <script src="~/Web2/plugins/sparklines/sparkline.js"></script>
    <script src="~/Web2/plugins/jqvmap/jquery.vmap.min.js"></script>
    <script src="~/Web2/plugins/jqvmap/maps/jquery.vmap.usa.js"></script>
    <script src="~/Web2/plugins/jquery-knob/jquery.knob.min.js"></script>
    <script src="~/Web2/plugins/moment/moment.min.js"></script>
    <script src="~/Web2/plugins/daterangepicker/daterangepicker.js"></script>
    <script src="~/Web2/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js"></script>
    <script src="~/Web2/plugins/summernote/summernote-bs4.min.js"></script>
    <script src="~/Web2/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js"></script>
    <script src="~/Web2/dist/js/adminlte.js"></script>
    <script src="~/Web2/dist/js/pages/dashboard.js"></script>
    <script src="~/Web2/dist/js/demo.js"></script>
</body>
</html>

MvcOnlineTicariOtomasyonSistemi/MvcOnlineTicariOtomasyonSistemi/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Fatura İşlemleri", "Dinamik", "Fatura", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Faturalar", "Dinamik", "Fatura")</li>
                    <li>@Html.ActionLink("Admin", "Index", "Kategori")</li>
                    <li>@Html.ActionLink("Yardım", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
      
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>