MvcOnlineTicariOtomasyonSistemi/MvcOnlineTicariOtomasyonSistemi/Controllers/SatisController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcOnlineTicariOtomasyonSistemi.Models.Siniflar;
namespace MvcOnlineTicariOtomasyonSistemi.Controllers
{
    public class SatisController : Controller
    {
        // GET: Satis
        Context c = new Context();
        public ActionResult Index()
        {
            var sorgu = c.SatisHarekets.ToList();
            return View(sorgu);
        }
        [HttpGet]
        public ActionResult YeniSatis()
        {
            List<SelectListItem> urun = (from x in c.Uruns.ToList()
                                         select new SelectListItem
                                         {
                                             Text = x.UrunAd,
                                             Value = x.UrunId.ToString()
                                         }).ToList();
            ViewBag.urn = urun;

            List<SelectListItem> cari = (from x in c.Carilers.ToList()
                                         select new SelectListItem
                                         {
                                             Text = x.CariAd + " " + x.CariSoyad,
                                             Value = x.CariId.ToString()
                                         }).ToList();
            ViewBag.cr = cari;

            List<SelectListItem> persnl = (from x in c.Personels.ToList()
                                         select new SelectListItem
                                         {
                                             Text = x.PersonelAd + " " + x.PersonelSoyad,
                                             Value = x.PersonelId.ToString()
                                         }).ToList();
            ViewBag.prsl = persnl;
            return View();
        }
        [HttpPost]
        public ActionResult YeniSatis(SatisHareket s)
        {
            s.Tarih = DateTime.Parse(DateTime.Now.ToShortDateString());
            c.SatisHarekets.Add(s);
            c.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult SatisGetir(int id)
        {
            List<SelectListItem> urun = (from x in c.Uruns.ToList()
                                         select new SelectListItem
                                         {
                                             Text = x.UrunAd,
                                             Value = x.UrunId.ToString()
                                         }).ToList();
            ViewBag.urn = urun;

            List<SelectListItem> cari = (from x in c.Carilers.ToList()
                                         select new SelectListItem
                                         {
                                             Text = x.CariAd + " " + x.CariSoyad,
                                             Value = x.CariId.ToString()
                                         }).ToList();
            ViewBag.cr = cari;

            List<SelectListItem> persnl = (from x in c.Personels.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.PersonelAd + " " + x.PersonelSoyad,
                                               Value = x.PersonelId.ToString()
                                           }).ToList();
            ViewBag.prsl = persnl;
            var sorgu = c.SatisHarekets.Find(id);
            return View("SatisGetir",sorgu);
        }
        public ActionResult SatisGuncelle(SatisHareket sts)
        {
            sts.Tarih = DateTime.Parse(DateTime.Now.ToShortDateString());
            var sorgu = c.SatisHarekets.Find(sts.SatisId);
            sorgu.Adet = sts.Adet;
            sorgu.Fiyat = sts.Fiyat;
            sorgu.ToplamTutar = sts.ToplamTutar;
            sorgu.CariId = sts.CariId;
            sorgu.PersonelId = sts.PersonelId;
            sorgu.UrunId = sts.UrunId;
            c.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult SatisDetay(int id)
        {
            var sorgu = c.SatisHarekets.Find(id);
            return View(sorgu);
        }
    }
}

MvcOnlineTicariOtomasyonSistemi/MvcOnlineTicariOtomasyonSistemi/Views/Satis/Index.cshtml
@using MvcOnlineTicariOtomasyonSistemi.Models.Siniflar
@model List<SatisHareket>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<br/>
<main>
    <div class="container-fluid">
        <h1 class="mt-4"></h1>
        <ol class="breadcrumb mb-4">
            <li class="breadcrumb-item active">Satış Hareketleri </li>
        </ol>
        <div class="card mb-4">
            <div class="card-header">
                <i class="fas fa-table mr-1"></i>
                Satış Hareket Listesi

            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <br/>
                    <table id="tbl1" class="table table-bordered" width="100%" cellspacing="0">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>TARİH</th>
                                <th>ADET</th>
                                <th>FİYAT</th>
                                <th>TOPLAM TUTAR</th>
                                <th>CARİ AD</th>
                                <th>PERSONEL ADI</th>
                                <th>ÜRÜN ADI</th>
                                <th>GÜNCELLE</th>
                                <th>DETAYLAR</th>

                            </tr>
                        </thead>
                     
                        <tbody>
                            @foreach (var s in Model)
                            {
                                <tr>
                                    <td>@s.SatisId</td>
                                    <td>@Convert.ToDateTime(s.Tarih).ToString("dd/MM/yyyy")</td>
                                    <td>@s.Adet</td>
                                    <td>@s.Fiyat</td>
                                    <td>@s.ToplamTutar</td>
                                    <td>@s.Cariler.CariAd @s.Cariler.CariSoyad</td>
                                    <td>@s.Personel.PersonelAd @s.Personel.PersonelSoyad</td>
                                    <td>@s.Urun.UrunAd</td>
                                    <td><a href="/Satis/SatisGetir/@s.SatisId" class="btn btn-success">GÜNCELLE</a></td>
                                    <td><a href="/Satis/SatisDetay/@s.SatisId" class="btn btn-warning">DETAYLAR</a></td>
                                </tr>
                            }
                        </tbody>
                    </table>
                    <a href="/Satis/YeniSatis/" class="btn btn-primary">YENİ SATIŞ YAP</a>
                </div>
            </div>
        </div>
    </div>
</main>


<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>


<link href="https://cdn.datatables.net/1.10.15/css/dataTables.bootstrap.min.css" rel="stylesheet" />
<link href="https://cdn.datatables.net/responsive/2.1.1/css/responsive.bootstrap.min.css" rel="stylesheet" />
<script src="https://cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.15/js/dataTables.bootstrap4.min.js"></script>

<script>
    $('#tbl1').dataTable({});
</script>

MvcOnlineTicariOtomasyonSistemi/MvcOnlineTicariOtomasyonSistemi/Views/Satis/SatisDetay.cshtml
@model MvcOnlineTicariOtomasyonSistemi.Models.Siniflar.SatisHareket
@{
    ViewBag.Title = "SatisDetay";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<main>
    <div class="container-fluid">
        <h1 class="mt-4"></h1>
        <ol class="breadcrumb mb-4">
            <li class="breadcrumb-item active">Satış Detay Sayfası</li>
        </ol>
        <div class="card mb-4">
            <div class="card-header">
                <i class="fas fa-table mr-1"></i>
            </div>
            <div class="card-body">
                <font size="4" color="red">@Html.Label("Satış No:", new { @class = "Form-control" })</font>
                <font size="4" color="black">@Html.DisplayTextFor(x => x.SatisId)</font>
                <br />
                <hr />
                <br />
                <font size="4" color="red">@Html.Label("Personel Adı ve Soyadı:", new { @class = "Form-control" })</font>
                <font size="4" color="black">@Html.DisplayTextFor(x => x.Personel.PersonelAd) @Html.DisplayTextFor(x => x.Personel.PersonelSoyad)</font>
                <br />
                <hr />
                <br />
                <font size="4" color="red">@Html.Label("Müşteri Adı ve Soyadı:", new { @class = "Form-control" })</font>
                <font size="4" color="black">@Html.DisplayTextFor(x => x.Cariler.CariAd) @Html.DisplayTextFor(x => x.Cariler.CariSoyad)</font>
                <br />
                <hr />
                <br />
                <font size="4" color="red">@Html.Label("Ürün Adı:", new { @class = "Form-control" })</font>
                <font size="4" color="black">@Html.DisplayTextFor(x => x.Urun.UrunAd)</font>
                <br />
                <hr />
                <br />
                <font size="4" color="red">@Html.Label("Satış Tarihi:", new { @class = "Form-control" })</font>
                <font size="4" color="black">@Html.DisplayTextFor(x => x.Tarih)</font>
                <br />
                <hr />
                <br />
                <font size="4" color="red">@Html.Label("Adet:", new { @class = "Form-control" })</font>
                <font size="4" color="black">@Html.DisplayTextFor(x => x.Adet)</font>
                <br />
                <hr />
                <br />
                <font size="4" color="red">@Html.Label("Ürün Fiyatı:", new { @class = "Form-control" })</font>
                <font size="4" color="black">@Html.DisplayTextFor(x => x.Fiyat)</font>
                <br />
                <hr />
                <br />
                <font size="4" color="red">@Html.Label("Toplam Tutar:", new { @class = "Form-control" })</font>
                <font size="4" color="black">@Html.DisplayTextFor(x => x.ToplamTutar)</font>
                <br />
                <hr />
                <br />
                <a href="#" class="btn btn-primary">YAZDIR</a>
            </div>
        </div>
</main>

MvcOnlineTicariOtomasyonSistemi/MvcOnlineTicariOtomasyonSistemi/Views/Satis/SatisGetir.cshtml
@model MvcOnlineTicariOtomasyonSistemi.Models.Siniflar.SatisHareket
@{
    ViewBag.Title = "SatisGetir";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<main>
    <div class="container-fluid">
        <h1 class="mt-4"></h1>
        <ol class="breadcrumb mb-4">
            <li class="breadcrumb-item active">Satış Güncelleme Sayfası</li>
        </ol>
        <div class="card mb-4">
            <div class="card-header">
                <i class="fas fa-table mr-1"></i>
            </div>
            <div class="card-body">
                @using (Html.BeginForm("SatisGuncelle", "Satis", FormMethod.Post))
                {
                    @Html.HiddenFor(x=>x.SatisId)
                    <font size="4" color="red">@Html.Label("Personel Adı:")</font>
                    @Html.DropDownListFor(x => x.PersonelId, (List<SelectListItem>)ViewBag.prsl, new { @class = "form-control" })
                    <br />
                    <font size="4" color="red">@Html.Label("Müşteri Adı:")</font>
                    @Html.DropDownListFor(x => x.CariId, (List<SelectListItem>)ViewBag.cr, new { @class = "form-control" })
                    <br />
                    <font size="4" color="red">@Html.Label("Adet:")</font>
                    @Html.TextBoxFor(x => x.Adet, new { @class = "form-control"})
                    <br />
                    <font size="4" color="red">@Html.Label("Ürün:")</font>
                    @Html.DropDownListFor(x => x.UrunId, (List<SelectListItem>)ViewBag.urn, new { @class = "form-control" })
                    <br />
                    <font size="4" color="red">@Html.Label("Fiyat:")</font>
                    @Html.TextBoxFor(x => x.Fiyat, new { @class = "form-control" })
                    <br />
                    <font size="4" color="red">@Html.Label("Toplam Tutar:")</font>
                    @Html.TextBoxFor(x => x.ToplamTutar, new { @class = "form-control" })
                    <br />
                    <button class="btn btn-primary">GÜNCELLE</button>
                }
            </div>
        </div>
</main>

MvcOnlineTicariOtomasyonSistemi/MvcOnlineTicariOtomasyonSistemi/Views/Satis/YeniSatis.cshtml
@model MvcOnlineTicariOtomasyonSistemi.Models.Siniflar.SatisHareket
@{
    ViewBag.Title = "YeniSatis";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<main>
    <div class="container-fluid">
        <h1 class="mt-4"></h1>
        <ol class="breadcrumb mb-4">
            <li class="breadcrumb-item active">Satış Sayfası</li>
        </ol>
        <div class="card mb-4">
            <div class="card-header">
                <i class="fas fa-table mr-1"></i>
            </div>
            <div class="card-body">
                <form class="form-group" method="post">
                    <font size="4" color="red">@Html.Label("Personel Adı:")</font>
                    @Html.DropDownListFor(x => x.PersonelId,(List<SelectListItem>)ViewBag.prsl, new { @class = "form-control" })
                    <br />
                    <font size="4" color="red">@Html.Label("Müşteri Adı:")</font>
                    @Html.DropDownListFor(x => x.CariId,(List<SelectListItem>)ViewBag.cr, new { @class = "form-control" })
                    <br />                   
                    <font size="4" color="red">@Html.Label("Adet:")</font>
                    @Html.TextBoxFor(x => x.Adet, new { @class = "form-control" })
                    <br />
                    <font size="4" color="red">@Html.Label("Ürün:")</font>
                    @Html.DropDownListFor(x => x.UrunId,(List<SelectListItem>)ViewBag.urn,new { @class = "form-control" })
                    <br />
                    <font size="4" color="red">@Html.Label("Fiyat:")</font>
                    @Html.TextBoxFor(x => x.Fiyat, new { @class = "form-control" })
                    <br />
                    <font size="4" color="red">@Html.Label("Toplam Tutar:")</font>
                    @Html.TextBoxFor(x => x.ToplamTutar, new { @class = "form-control" })
                    <br />
                    <button class="btn btn-info">SATIŞ YAP</button>
                </form>
            </div>
        </div>
</main>