MvcOnlineTicariOtomasyonSistemi/MvcOnlineTicariOtomasyonSistemi/Controllers/IstatistikController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcOnlineTicariOtomasyonSistemi.Models.Siniflar;
namespace MvcOnlineTicariOtomasyonSistemi.Controllers
{
    public class IstatistikController : Controller
    {
        // GET: Istatistik
        Context c = new Context();
        public ActionResult Index()
        {
            //toplam cari sayısı
            var deger1 = c.Carilers.Count().ToString();
            ViewBag.d1 = deger1;

            //toplam ürün sayısı
            var deger2 = c.Uruns.Count().ToString();
            ViewBag.d2 = deger2;

            //personel sayısı
            var deger3 = c.Personels.Count().ToString();
            ViewBag.d3 = deger3;

            //kategori sayısı
            var deger4 = c.Kategoris.Count().ToString();
            ViewBag.d4 = deger4;

            //toplam stok
            var deger5 = c.Uruns.Sum(x => x.Stok).ToString();
            ViewBag.d5 = deger5;

            //marka sayısı
            var deger6 = (from x in c.Uruns select x.Marka).Distinct().Count().ToString();
            ViewBag.d6 = deger6;

            //kritik seviye
            var deger7 = c.Uruns.Count(x => x.Stok <= 20).ToString();
            ViewBag.d7 = deger7;

            //max. fiyatlı ürün
            var deger8 = (from x in c.Uruns orderby x.SatisFiyati descending select x.UrunAd).FirstOrDefault();
            ViewBag.d8 = deger8;

            //min. fiyatlı Ürün
            var deger9 = (from x in c.Uruns orderby x.SatisFiyati ascending select x.UrunAd).FirstOrDefault();
            ViewBag.d9 = deger9;

            //max.marka
            var deger10 = c.Uruns.GroupBy(x => x.Marka).OrderByDescending(z => z.Count()).Select(y => y.Key).FirstOrDefault();
            ViewBag.d10 = deger10;

            //buzdolabı stok sayısı
            var deger11 = c.Uruns.Where(x => x.UrunAd == "Buzdolabı").Sum(x => x.Stok).ToString();
            ViewBag.d11 = deger11;

            //laptop sayısı
            var deger12 = c.Uruns.Count(x => x.UrunAd == "Laptop").ToString();
            ViewBag.d12 = deger12;

            //en çok satan ürün
            var deger13 = c.Uruns.Where(u=>u.UrunId==(c.SatisHarekets.GroupBy(x => x.UrunId).OrderByDescending(z=>z.Sum(k=>k.Adet)).Select(y => y.Key).FirstOrDefault())).Select(t=>t.UrunAd).FirstOrDefault();
            ViewBag.d13 = deger13;

            //kasadaki tutar
            var deger14 = c.SatisHarekets.Sum(x => x.ToplamTutar).ToString();
            ViewBag.d14 = deger14;

            //bugünkü satış miktarı
            DateTime bugun1 = DateTime.Today;
            var deger15 = c.SatisHarekets.Count(x => x.Tarih == bugun1).ToString();
            ViewBag.d15 = deger15;

            //bugünkü kasa
            //DateTime bugun=DateTime.Today; 'de yazabilirdik.
            DateTime bugun2 =DateTime.Parse( DateTime.Now.ToShortDateString());
            var deger16 = c.SatisHarekets.Where(x => x.Tarih == bugun2).Sum(y =>(decimal?)y.ToplamTutar).ToString();
            ViewBag.d16 = deger16;
            return View();
        }

        public ActionResult KolayTablolar()
        {                     
            return View();
        }
        public PartialViewResult Partial1()
        {
            var sorgu = from x in c.Carilers
                        group x by x.CariSehir into g
                        select new GrupSinif
                        {
                            Sehir = g.Key, //Grubun içerisine dahil olacak alan
                            Sayi = g.Count() //grubumuzun ilgili sayıcağı ifadesi
                        };
            return PartialView(sorgu.ToList());
        }
        public PartialViewResult Partial()
        {
            var sorgu = from x in c.Personels
                        group x by x.Departman.DepartmanAd into g
                        select new GrupSinif2
                        {
                            Departman = g.Key,
                            Sayi = g.Count()
                        };
            return PartialView(sorgu.ToList());
        }

        public PartialViewResult Partial2()
        {
            var sorgu = c.Carilers.Where(x=>x.Durum==true).ToList();
            return PartialView(sorgu);
        }
        public PartialViewResult Partial3()
        {
            var sorgu = c.Uruns.Where(x => x.Durum == true).ToList();
            return PartialView(sorgu);
        }
        public PartialViewResult Partial4()
        {
            var sorgu = from x in c.Uruns
                        group x by x.Marka into g
                        select new GrupSinif3
                        {
                            Marka = g.Key,
                            Sayi = g.Count()
                        };
            return PartialView(sorgu.ToList());
        }
    }
}

MvcOnlineTicariOtomasyonSistemi/MvcOnlineTicariOtomasyonSistemi/Views/Istatistik/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

    <main>
        <div class="container-fluid">
            <h1 class="mt-4"></h1>
            <ol class="breadcrumb mb-4">
                <li class="breadcrumb-item active">İstatistikler</li>
            </ol>
            <div class="row">
                <div class="col-xl-3 col-md-6">
                    <div class="card" style="background-color:#1abc9c">
                        <div class="card-body"><h3>@ViewBag.d1</h3></div>
                        <div class="card-footer d-flex align-items-center justify-content-between">
                            <p>TOPLAM CARİ</p>
                        </div>
                    </div>
                </div>
                <div class="col-xl-3 col-md-6">
                    <div class="card" style="background-color:#2ecc71">
                        <div class="card-body"><h3>@ViewBag.d2</h3></div>
                        <div class="card-footer d-flex align-items-center justify-content-between">
                            <p>ÜRÜN SAYISI</p>
                        </div>
                    </div>
                </div>
                <div class="col-xl-3 col-md-6">
                    <div class="card" style="background-color:#3498db">
                        <div class="card-body"><h3>@ViewBag.d3</h3></div>
                        <div class="card-footer d-flex align-items-center justify-content-between">
                            <p>PERSONEL SAYISI</p>
                        </div>
                    </div>
                </div>
                <div class="col-xl-3 col-md-6">
                    <div class="card" style="background-color:#9b59b6">
                        <div class="card-body"><h3>@ViewBag.d4</h3></div>
                        <div class="card-footer d-flex align-items-center justify-content-between">
                            <p>KATEGORİ SAYISI</p>
                        </div>
                    </div>
                </div>

            </div>
            <br />
            <div class="row">
                <div class="col-xl-3 col-md-6">
                    <div class="card" style="background-color:#16a085">
                        <div class="card-body"><h3>@ViewBag.d5</h3></div>
                        <div class="card-footer d-flex align-items-center justify-content-between">
                            <p>TOPLAM STOK</p>
                        </div>
                    </div>
                </div>
                <div class="col-xl-3 col-md-6">
                    <div class="card" style="background-color:#27ae60">
                        <div class="card-body"><h3>@ViewBag.d6</h3></div>
                        <div class="card-footer d-flex align-items-center justify-content-between">
                            <p>MARKA SAYISI</p>
                        </div>
                    </div>
                </div>
                <div class="col-xl-3 col-md-6">
                    <div class="card" style="background-color:#2980b9">
                        <div class="card-body"><h3>@ViewBag.d7</h3></div>
                        <div class="card-footer d-flex align-items-center justify-content-between">
                            <p>KRİTİK SEVİYE</p>
                        </div>
                    </div>
                </div>
                <div class="col-xl-3 col-md-6">
                    <div class="card" style="background-color:#8e44ad">
                        <div class="card-body"><h3>@ViewBag.d8</h3></div>
                        <div class="card-footer d-flex align-items-center justify-content-between">
                            <p>MAX. FİYATLI ÜRÜN</p>
                        </div>
                    </div>
                </div>
            </div>
            <br />
            <div class="row">
                <div class="col-xl-3 col-md-6">
                    <div class="card" style="background-color:#f1c40f">
                        <div class="card-body"><h3>@ViewBag.d9</h3></div>
                        <div class="card-footer d-flex align-items-center justify-content-between">
                            <p>MİN. FİYATLI ÜRÜN</p>
                        </div>
                    </div>
                </div>
                <div class="col-xl-3 col-md-6">
                    <div class="card" style="background-color:#e67e22">
                        <div class="card-body"><h3>@ViewBag.d10</h3></div>
                        <div class="card-footer d-flex align-items-center justify-content-between">
                            <p>MAX. MARKA</p>
                        </div>
                    </div>
                </div>
                <div class="col-xl-3 col-md-6">
                    <div class="card" style="background-color:#e74c3c">
                        <div class="card-body"><h3>@ViewBag.d11</h3></div>
                        <div class="card-footer d-flex align-items-center justify-content-between">
                            <p>BUZDOLABI STOK SAYISI</p>
                        </div>
                    </div>
                </div>
                <div class="col-xl-3 col-md-6">
                    <div class="card" style="background-color:#95a5a6">
                        <div class="card-body"><h3>@ViewBag.d12</h3></div>
                        <div class="card-footer d-flex align-items-center justify-content-between">
                            <p>LAPTOP MARKA SAYISI</p>
                        </div>
                    </div>
                </div>
            </div>
            <br />
            <div class="row">
                <div class="col-xl-3 col-md-6">
                    <div class="card" style="background-color:#f39c12">
                        <div class="card-body"><h3>@ViewBag.d13</h3></div>
                        <div class="card-footer d-flex align-items-center justify-content-between">
                            <p>EN ÇOK SATAN ÜRÜN</p>
                        </div>
                    </div>
                </div>
                <div class="col-xl-3 col-md-6">
                    <div class="card" style="background-color:#d35400">
                        <div class="card-body"><h3>@ViewBag.d14</h3></div>
                        <div class="card-footer d-flex align-items-center justify-content-between">
                            <p>KASADAKİ TUTAR</p>
                        </div>
                    </div>
                </div>
                <div class="col-xl-3 col-md-6">
                    <div class="card" style="background-color:#c0392b">
                        <div class="card-body"><h3>@ViewBag.d15</h3></div>
                        <div class="card-footer d-flex align-items-center justify-content-between">
                            <p>BUGÜNKÜ SATIŞ MİKTARI </p>
                        </div>
                    </div>
                </div>
                <div class="col-xl-3 col-md-6">
                    <div class="card" style="background-color:#7f8c8d">
                        <div class="card-body"><h3>@ViewBag.d16</h3></div>
                        <div class="card-footer d-flex align-items-center justify-content-between">
                            <p>BUGÜNKÜ KASA</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>

MvcOnlineTicariOtomasyonSistemi/MvcOnlineTicariOtomasyonSistemi/Views/Istatistik/KolayTablolar.cshtml
@{
    ViewBag.Title = "KolayTablolar";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />
<div class="wrapper">

    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-6">

                    @Html.Action("Partial4", "Istatistik")

                    <br />
                    @Html.Action("Partial", "Istatistik")
                </div>
                @Html.Action("Partial1", "Istatistik")
            </div>
            @Html.Action("Partial2","Istatistik")
            @Html.Action("Partial3","Istatistik")
        </div>
    </section>
</div>
<script src="~/Web2/plugins/jquery/jquery.min.js"></script>
<script src="~/Web2/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<script src="~/Web2/dist/js/adminlte.min.js"></script>
<script src="~/Web2/dist/js/demo.js"></script>

<link rel="stylesheet" href="~/Web2/plugins/fontawesome-free/css/all.min.css">
<link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
<link rel="stylesheet" href="~/Web2/dist/css/adminlte.min.css">
<link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">

MvcOnlineTicariOtomasyonSistemi/MvcOnlineTicariOtomasyonSistemi/Views/Istatistik/Partial.cshtml
@model IEnumerable<MvcOnlineTicariOtomasyonSistemi.Models.Siniflar.GrupSinif2>
<div class="card">
    <div class="card-header">
        <h3 class="card-title">DEPARTMAN PERSONEL SAYISI</h3>
    </div>
    <div class="card-body p-0">
        <table class="table table-sm">
            <thead>
                <tr>
                    <th style="width: 10px">#</th>
                    <th>DEPARTMAN AD</th>
                    <th>PROGRESS BAR</th>
                    <th style="width: 40px">ADET</th>
                </tr>
            </thead>
            <tbody>
                @{ int sirano = 0;}
                @foreach (var x in Model)
                {
                <tr>
                    <td>@{sirano++;} @sirano</td>
                    <td>@x.Departman</td>
                    <td>
                        @if (x.Sayi == 1)
                        {
                        <div class="progress progress-xs">
                            <div class="progress-bar progress-bar-danger" style="width: 55%"></div>
                        </div>
                        }
                        @if (x.Sayi == 2)
                        {
                        <div class="progress progress-xs">
                            <div class="progress-bar bg-warning" style="width: 70%"></div>
                        </div>
                        }
                        @if (x.Sayi == 3)
                        {
                        <div class="progress progress-xs progress-striped active">
                            <div class="progress-bar bg-primary" style="width: 30%"></div>
                        </div>
                        }
                        @if (x.Sayi == 4)
                        {
                        <div class="progress progress-xs progress-striped active">
                            <div class="progress-bar bg-success" style="width: 90%"></div>
                        </div>
                        }
                    </td>
                    <td>
                        @if (x.Sayi == 1)
                        {
                            <span class="badge bg-danger">@x.Sayi</span>
                        }
                        @if (x.Sayi == 2)
                        {
                            <span class="badge bg-warning">@x.Sayi</span>
                        }
                        @if (x.Sayi == 3)
                        {
                            <span class="badge bg-primary">@x.Sayi</span>
                        }
                        @if (x.Sayi == 4)
                        {
                            <span class="badge bg-success">@x.Sayi</span>
                        }
                    </td>
                </tr>
                }               
            </tbody>
        </table>
    </div>
</div>

MvcOnlineTicariOtomasyonSistemi/MvcOnlineTicariOtomasyonSistemi/Views/Istatistik/Partial1.cshtml
@model IEnumerable<MvcOnlineTicariOtomasyonSistemi.Models.Siniflar.GrupSinif>
<!--harici olarak sınıf kullandığmız için ve controller tarafından o sınıftan değer çektiğim için IEnumerable<> kullanacağız yukarıda modeli tanımladığımız yerde-->
<div class="col-md-6">
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Müşteri Şehir Tablosu</h3>
            <div class="card-tools">

            </div>
        </div>
        <div class="card-body p-0">
            <table class="table">
                <thead>
                    <tr>
                        <th style="width: 10px">#</th>
                        <th>ŞEHİR</th>
                        <th>PROGRESS BAR</th>
                        <th style="width: 40px">ADET</th>
                    </tr>
                </thead>
                <tbody>
                    @{ int sirano = 0;}
                    @foreach (var x in Model)
                    {
                        <tr>
                            <td>@{sirano++;} @sirano</td>
                            <td>@x.Sehir</td>
                            <td>
                                @if (x.Sayi == 1)
                                {
                                    <div class="progress progress-xs">
                                        <div class="progress-bar progress-bar-danger" style="width: 55%"></div>
                                    </div>
                                }
                                @if (x.Sayi == 2)
                                {
                                    <div class="progress progress-xs">
                                        <div class="progress-bar bg-warning" style="width: 70%"></div>
                                    </div>
                                }
                                @if (x.Sayi == 3)
                                {
                                    <div class="progress progress-xs progress-striped active">
                                        <div class="progress-bar bg-primary" style="width: 30%"></div>
                                    </div>
                                }
                                @if (x.Sayi == 4)
                                {
                                    <div class="progress progress-xs progress-striped active">
                                        <div class="progress-bar bg-success" style="width: 90%"></div>
                                    </div>
                                }

                            </td>
                            <td>
                                @if (x.Sayi == 1)
                                {
                                    <span class="badge bg-danger">@x.Sayi</span>
                                }
                                @if (x.Sayi == 2)
                                {
                                    <span class="badge bg-warning">@x.Sayi</span>
                                }
                                @if (x.Sayi == 3)
                                {
                                    <span class="badge bg-primary">@x.Sayi</span>
                                }
                                @if (x.Sayi == 4)
                                {
                                    <span class="badge bg-success">@x.Sayi</span>
                                }

                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>

</div>

MvcOnlineTicariOtomasyonSistemi/MvcOnlineTicariOtomasyonSistemi/Views/Istatistik/Partial2.cshtml
@using MvcOnlineTicariOtomasyonSistemi.Models.Siniflar
@model List<Cariler>
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">CARİLER TABLOSU</h3>
                <div class="card-tools">
                    <div class="input-group input-group-sm" style="width: 150px;">
                        
                        <div class="input-group-append">
                           
                        </div>
                    </div>
                </div>
            </div>
            <div class="card-body table-responsive p-0">
                <table class="table table-hover text-nowrap">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>AD</th>
                            <th>SOYAD</th>
                            <th>ŞEHİR</th>
                            <th>MAİL</th>                    
                        </tr>
                    </thead>
                    <tbody>
                        @{ int sirano = 0;}
                        @foreach (var c in Model)
                        {
                        <tr>
                            <td>@{sirano++;} @sirano</td>
                            <td>@c.CariAd</td>
                            <td>@c.CariSoyad</td>
                            <td>@c.CariSehir</td>
                            <td>@c.CariMail</td>
                        </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

MvcOnlineTicariOtomasyonSistemi/MvcOnlineTicariOtomasyonSistemi/Views/Istatistik/Partial3.cshtml
@using MvcOnlineTicariOtomasyonSistemi.Models.Siniflar
@model List<Urun>
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">ÜRÜNLER TABLOSU</h3>
                <div class="card-tools">
                    <div class="input-group input-group-sm" style="width: 150px;">
                        
                        <div class="input-group-append">
                            
                        </div>
                    </div>
                </div>
            </div>
            <div class="card-body table-responsive p-0" style="height: 300px;">
                <table class="table table-head-fixed text-nowrap">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>ÜRÜN ADI</th>
                            <th>MARKA ADI</th>
                            <th>STOK</th>
                            <th>ALIŞ FİYATI</th>
                            <th>SATIŞ FİYATI</th>
                            <th>ÜRÜN RESMİ</th>
                            <th>KATEGORİ ADI</th>
                        </tr>
                    </thead>
                    <tbody>
                        @{ int sirano=0;}
                        @foreach (var u in Model)
                        {
                        <tr>
                            <td>@{sirano++;} @sirano</td>
                            <td>@u.UrunAd</td>
                            <td>@u.Marka</td>
                            <td>@u.Stok</td>
                            <td>@u.AlisFiyati ₺</td>
                            <td>@u.SatisFiyati ₺</td>
                            <td>@u.UrunGorsel</td>
                            <td>@u.Kategori.KategoriAd</td>
                        </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

MvcOnlineTicariOtomasyonSistemi/MvcOnlineTicariOtomasyonSistemi/Views/Istatistik/Partial4.cshtml
@model IEnumerable<MvcOnlineTicariOtomasyonSistemi.Models.Siniflar.GrupSinif3>
<div class="card">
    <div class="card-header">
        <h3 class="card-title">MARKA SAYILARI</h3>
    </div>
    <div class="card-body p-0">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th style="width: 10px">#</th>
                    <th>MARKA</th>
                    <th>PROGRESS BAR</th>
                    <th style="width: 40px">ADET</th>
                </tr>
            </thead>
            <tbody>
                @{int sirano = 0;}
                @foreach (var x in Model)
                {
                <tr>
                    <td>@{sirano++;} @sirano</td>
                    <td>@x.Marka</td>
                    <td>
                        @if (x.Sayi == 1)
                        {
                            <div class="progress progress-xs">
                                <div class="progress-bar progress-bar-danger" style="width: 55%"></div>
                            </div>
                        }
                        @if (x.Sayi == 2)
                        {
                            <div class="progress progress-xs">
                                <div class="progress-bar bg-warning" style="width: 70%"></div>
                            </div>
                        }
                        @if (x.Sayi == 3)
                        {
                            <div class="progress progress-xs progress-striped active">
                                <div class="progress-bar bg-primary" style="width: 30%"></div>
                            </div>
                        }
                        @if (x.Sayi == 4)
                        {
                            <div class="progress progress-xs progress-striped active">
                                <div class="progress-bar bg-success" style="width: 90%"></div>
                            </div>
                        }
                    </td>
                    <td>
                        @if (x.Sayi == 1)
                        {
                            <span class="badge bg-danger">@x.Sayi</span>
                        }
                        @if (x.Sayi == 2)
                        {
                            <span class="badge bg-warning">@x.Sayi</span>
                        }
                        @if (x.Sayi == 3)
                        {
                            <span class="badge bg-primary">@x.Sayi</span>
                        }
                        @if (x.Sayi == 4)
                        {
                            <span class="badge bg-success">@x.Sayi</span>
                        }
                    </td>
                </tr>
                }
               
            </tbody>
        </table>
    </div>
</div>